title: "Spark-AE"
description: "Spark-AE is a synth module designed for the AE Modular format. It is based on the Daisy Seed embedded DSP platform."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
